name: DegreeSmart Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'microsoft'
    - name: Compile all .java files with javac
      shell: pwsh
      run: javac -Xlint:unchecked -d bin -cp "lib/json-simple-1.1.1.jar" $(foreach ($File in (Get-ChildItem degreesmart | Where-Object Name -like "*.java")) { "degreesmart/$($File.Name)"})
